run:
  deadline: 15m

linters:
  disable-all: true
  enable:
    - contextcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - sqlclosecheck
    - unconvert
    - unused
