name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.20']
    steps:
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 #v4.0.1
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.2"
      - name: Build
        run: go build ./...
      - name: Lint
        run: golangci-lint run
